hw-3
emilkhairullin/kts-project pull request #1
Opened 2022-08-26 23:07 UTC by emilkhairullin

2022-08-30 12:00 UTC, pavellap requested changes
В целом всё очень хорошо, знаешь про семантику, выносишь всё в отдельные файлы, но советую повнимательнее работать со стилями и больше внимания уделять правильному структурированию файлов

2022-08-30 12:00 UTC, pavellap commented on src/App/App.tsx
> +import "./App.css";
Файл можно опустить, он всё равно пустой)

2022-08-30 12:00 UTC, pavellap commented on src/App/App.tsx
> +import { NotFound } from "@pages/NotFound";
Правильно организовал импорты, лайк)

2022-08-30 12:00 UTC, pavellap commented on src/App/api/api.ts
> +const Client = axios.create({ baseURL: API_URL });
Молодца, хорошая практика создавать экземпляр с определённым базовым урлом

2022-08-30 12:00 UTC, pavellap commented on src/App/api/api.ts
> +export const getProducts = async () => {
Вкусовщина, но можно добавить тип возвращаемого значения, чтобы вообще по красоте был: `Promise<Product[]>`

2022-08-30 12:00 UTC, pavellap commented on src/App/api/api.ts
> +const Client = axios.create({ baseURL: API_URL });
Смотри, идея на подумать: можно создать отдельно функцию или хук для запросов: в него можно включить следующие состояния:
1. isLoading
2. isError
Таким образом избавимся от дублирования логики с индикацией загрузки и перехватыванием ошибок)

2022-08-30 12:00 UTC, pavellap commented on src/App/api/hooks/useCategories.tsx
> +      })();
моё уважение за IIFE, редко используемая конструкция, но здесь всё правильно

2022-08-30 12:00 UTC, pavellap commented on src/App/api/hooks/useCategories.tsx
> +  const [loading, setLoading] = useState(true);
Изначально всё же лучше делать состояния в `false`, а затем его перед самой загрузкой закидывать в `true`, чтобы избежать различных неожиданных эффектов

2022-08-30 12:00 UTC, pavellap commented on src/App/api/hooks/useProduct.tsx
> +  const [loading, setLoading] = useState(false);
Как раз дропнется повторяемая логика, если вынесешь Client в отдельную утилиту

2022-08-30 12:00 UTC, pavellap commented on src/App/api/hooks/useProducts.tsx
> +    if (!products) return null;
по кодстайлу всё-таки советую использовать {}, код будет легче восприниматься

2022-08-30 12:00 UTC, pavellap commented on src/App/api/hooks/useProducts.tsx
> +  const filterProducts = () => {
Для оптимизации можно обернуть в `useCallback`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Button/Button.module.scss
> +  color: white;
Всё-таки даже такие мелочи лучше выносить в отдельные переменные, на больших проектах может быть несколько разных белых цветов

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Button/Button.module.scss
> +@import "../../styles/variables";
Попробуй абсолютный импорт `~styles/variables`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Button/Button.tsx
> +  const cx = classNames(
Попробуй оптимизировать, добавив мемоизацию через `React.useMemo`

2022-08-30 12:00 UTC, pavellap commented on src/index.scss
> +  @media screen {
можно дропнуть

2022-08-30 12:00 UTC, pavellap commented on src/App/utils/truncateText.ts
> +    let substring = input.substring(0, 40);
Можно красивее и проще навернуть: return input.slice(0, -1) + '...'

2022-08-30 12:00 UTC, pavellap commented on src/App/utils/truncateText.ts
> +  if (input.length > 50) {
+ опционально передавать количество образаемых символов в параметрах функции, чтобы её можно было переиспользовать

2022-08-30 12:00 UTC, pavellap commented on src/App/interfaces/product.interface.ts
> +export interface Rating {
Всё же лучше использовать типы для описания каких-то сущностей, интерфейсы правильнее использовать вместе с ооп
+ на будущее, все интерфейсы стараемся именовать с префикса I, то есть здесь было бы `IRating`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Button/Button.module.scss
> +  &--loading {
насколько я понял, ты в других файлах придерживался БЭМ, что в совокупности  с css-модулями даёт хорошую изоляцию
Но здесь у тебя поплыли названия классов по БЭМ
Модификаторы у нас идут через постфикс `classname_modificator`,
Элементы используются через постфикс `classname__element`
Таким образом, вместо `&--loading`, тебе следует записать`&_loading`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Button/Button.module.scss
> +  &_color--primary {
для цвета можно сокращённую нотацию использовать:
`&_color {
   &-primary {...}
   &-secondary {...}
}`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Button/Button.module.scss
> +  &_loader {
а здесь это элемент, соответственно получаем `&__loader`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Button/Button.module.scss
> +    fill: white !important;
без `!important` не работает? Всегда надо стараться избегать это правило, когда есть возможность

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Card/Card.module.scss
> +    line-height: 130%;
старайся указывать всё-таки в абсолютных значениях, - `18 * 1.3`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Card/Card.tsx
> +export const Card = ({
Старайся всё-таки использовать импорты по умолчанию, так получится в будущем избежать циклических зависимостей при импортах + не забывай про `React.memo`, который даёт нам оптимизацию

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Card/Card.module.scss
> +    margin: 0;
А зачем ты сбрасываешь внешние отступы? Их по идее и так не должно быть

2022-08-30 12:00 UTC, pavellap commented on src/App/components/CheckBox/CheckBox.tsx
> +      onChange={() => onClick()}
Можно сокращённую нотацию использовать, `onChange={onClick}`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Input/Input.module.scss
> +@import "../../styles/variables";
Не забываем про абсолютные импорты

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Input/Input.tsx
> +  naked = "naked",
Не совсем понял, а для чего этот цвет? В uikitе у нас вроде только один цвет у инпута

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Input/Input.tsx
> +      onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
Можно `useCallback` использовать

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Loader/Loader.module.scss
> +.loader_size-s {
старайся использовать по-максимуму возможности scss и группировать одинаковые группы селекторов

2022-08-30 12:00 UTC, pavellap commented on src/App/components/Loader/Loader.tsx
> +      {loading && (
Смотри, с loading логика немного другая должна быть: мы всегда в `Loader` отрисовываем анимированный спиннер, а сам компонент уже рендерим по флагу `isLoading`, то есть получаем конструкцию в духе: `isLoading ? <Loader/> : <Content>....</Content>`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/ReadMore/ReadMore.tsx
> +      <span
На самом деле можно сделать проще: `isTruncable && <span>Read more</span>`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/ReadMore/ReadMore.tsx
> +export const ReadMore = ({ description, limit, className }: ReadMoreProps) => {
Молодец, что догадался в отдельный компонент вынести! Не забывай про оптимизацию с `React.memo`

2022-08-30 12:00 UTC, pavellap commented on src/App/components/ReadMore/hooks/useTruncatedText.tsx
> +export const useTruncatedText = (full_text: string, limit: number) => {
Вынеси хук пожалуйста в `src/hooks`, всё-таки надо единой структуры в проекте придерживаться

2022-08-30 12:00 UTC, pavellap commented on src/App/components/WithLoader/WithLoader.module.scss
> +    height: 100%;
Можешь поработать с миксинами и создать миксин `square`, принимающий параметр `size` и возвращающий `width: size; height: size`;

2022-08-30 12:00 UTC, pavellap commented on src/App/config/api.config.ts
> +export const PRODUCTS_COUNT = 20;
Можно как раз количество продуктов на страницу ещё сюда вынести, а так молодец, что всё в конфиг вынес

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Footer/Footer.tsx
> +export const Footer = () => {
Не забываем про оптимизацию

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Footer/Footer.module.scss
> +  height: 120px;
Старайся не задавать фикс высоту, а разруливать всё через вертикальные паддинги

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Footer/Footer.module.scss
> +    &:nth-child(1) {
`:first-child`

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Header/Header.tsx
> +      <div className={`container ${styles.header__container}`}>
не забывай использовать `classnames`

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Header/Header.module.scss
> +  height: 120px;
Аналогично про высоту, старайся вертикальные паддинги использовать

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Header/Header.module.scss
> +  @media only screen and (max-width: 480px) {
Предлагаю создать миксин, который будет принимать в себя breakpoint и соответствующие стили для него
Пиши в личку, если будут вопросы касательно реализации

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Header/components/IconButton/IconButton.module.scss
> +  gap: 24px;
Хорошо знаешь про новые свойства)

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Header/components/IconButton/IconButton.tsx
> +export const IconButton = () => {
Вот этот компонент точно выносим в `src/components`

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Header/components/Logo/Logo.tsx
> +  className: string;
Этот параметр точно всегда должен быть опциональным, не всегда логотипу понадобится дополнительное позиционирование

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Header/components/Logo/Logo.tsx
> +export const Logo = ({ className }: LogoProps) => {
Логотип тоже выносим в `src/components` + не забываем про типизацию компонентов `Logo: React.FC<LogoProps>`

2022-08-30 12:00 UTC, pavellap commented on src/App/layouts/MainLayout/components/Header/components/Logo/Logo.tsx
> +
Просмотри весь свой PR на предмет пустых файлов со стилями и вычисти их

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/EmptyPage/EmptyPage.tsx
> +export const EmptyPage = () => {
React.memo

2022-08-30 12:00 UTC, pavellap commented on src/App/styles/_variables.scss
> +$page-min-height: calc(100vh - 240px);
А откуда вообще это число берётся? Мы должны стараться задавать высоту всему body через проценты и потом растягивать дочерние компоненты на всю высоту через `height: 100%`

2022-08-30 12:00 UTC, pavellap commented on src/App/utils/convertCategoriesToOptions.ts
> +  categories: string[] | null
Лучше всё-таки принимать только массив строк, и не выкидывать ошибку.
Если у тебя null, то просто не рендерить какие-либо элементы

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/SingularProduct/components/RelatedItems/RelatedItems.tsx
> +              image={product.image}
можно просто `<Card {...product}/>`

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/SingularProduct/components/ProductDisplay/components/VariationPicker/VariationPicker.tsx
> +  color: string;
Цвета лучше инкапсулировать внутри этого компонента или вообще вынести в enum

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/SingularProduct/components/ProductDisplay/components/VariationPicker/VariationPicker.tsx
> +              key={variation.name}
Аккуратнее с этим! В теории у тебя в одном массиве могут оказаться одинаковые имена и куча других сайдэффектор будет из-за этого

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/SingularProduct/components/ProductDisplay/components/VariationPicker/VariationPicker.tsx
> +              style={{ backgroundColor: variation.color }}
лучше вынести все цвета в файлы со стилями и задавать их через енамы

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/SingularProduct/components/ProductDisplay/ProductDisplay.tsx
> +    { name: "Variation 1", color: "#151411" },
соответственно эти цвета попадут в variationPicker у тебя

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/SingularProduct/components/ProductDisplay/ProductDisplay.tsx
> +            console.log(`${variation.name} was clicked!`)
не забудь вычистить)

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/SingularProduct/SingularProduct.tsx
> +  const pageStyles = classNames(styles["singular-page"], "container");
Лучше в самом теге задавать

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/Home/components/Hero/components/Controlls/Controlls.tsx
> +import icon_search from "@assets/icon-search.svg";
Следи за неймингом, у нас только camelCase или PascalCase

2022-08-30 12:00 UTC, pavellap commented on src/App/pages/Home/components/Hero/Hero.tsx
> +export const Hero = () => {
А почему такой нейминг? Не совсем очевидно, почему ты так назвал

2022-09-01 08:50 UTC, emilkhairullin commented on src/App/pages/Home/components/Hero/Hero.tsx
> +export const Hero = () => {
Hero  Section - первый элемент на главной странице.

2022-09-01 08:50 UTC, emilkhairullin commented on src/App/pages/Home/components/Hero/components/Controlls/Controlls.tsx
> +import icon_search from "@assets/icon-search.svg";
Учту, спасибо!

2022-09-01 08:59 UTC, emilkhairullin commented on src/App/layouts/MainLayout/components/Header/components/Logo/Logo.tsx
> +  className: string;
сделано

2022-09-01 09:02 UTC, emilkhairullin commented on src/App/layouts/MainLayout/components/Header/Header.tsx
> +      <div className={`container ${styles.header__container}`}>
Сделано

2022-09-01 09:02 UTC, emilkhairullin commented on src/App/layouts/MainLayout/components/Footer/Footer.module.scss
> +    &:nth-child(1) {
Да, проглядел. Сделано

2022-09-01 09:03 UTC, emilkhairullin commented on src/App/layouts/MainLayout/components/Footer/Footer.tsx
> +export const Footer = () => {
Сделано

2022-09-01 09:05 UTC, emilkhairullin commented on src/App/components/ReadMore/hooks/useTruncatedText.tsx
> +export const useTruncatedText = (full_text: string, limit: number) => {
Просто в лекции говорилось, что хуки, специфичные только для данного компонента, должны лежать в одной папке с данным компонентом. У меня в папке api тоже есть папка hooks. Их тоже в корневую папку с хуками вынести?

2022-09-01 09:05 UTC, emilkhairullin commented on src/App/components/ReadMore/ReadMore.tsx
> +      <span
Спасибо. Учту

2022-09-01 09:08 UTC, emilkhairullin commented on src/App/components/Loader/Loader.module.scss
> +.loader_size-s {
Спасибо. Видимо, при переносе с css на scss проглядел данный файл.

2022-09-01 09:12 UTC, emilkhairullin commented on src/App/components/Input/Input.tsx
> +  naked = "naked",
Да,  в uikite нет такого параметра, но мне захотелось переиспользовать данный компонент на главной странице, в блоке с поиском по товарам.

2022-09-01 09:12 UTC, emilkhairullin commented on src/App/components/Input/Input.module.scss
> +@import "../../styles/variables";
Сделано

2022-09-01 09:13 UTC, emilkhairullin commented on src/App/components/CheckBox/CheckBox.tsx
> +      onChange={() => onClick()}
Сделано

2022-09-07 14:44 UTC, merged